spring:
    application:
        name: CustomerDetails
    

       
server:
    port: ${port:8090}
# EUREKA
eureka:
  instance:
    hostname: localhost
    port: 8081
    
  client:
    serviceUrl:
      defaultZone: http://localhost:8081/eureka/
    registerWithEureka: true
    fetchRegistry: true